### ISSUE TITLE
Can you set this case in TWain?

### ISSUE THREAD

**Issue by mummyildiz** [cyanfish/naps2-wia#1]
Thank you for your project.

Can you set this case in TWain?

**Comment by cyanfish** [comment]
I'm not sure I understand the question. But this library is WIA-only. Eventually I'll publish NAPS2.Sdk with Twain support but that's a work in progress.

**Comment by mummyildiz** [comment]
Can you add similar TWain usage to this project?

**Comment by cyanfish** [comment]
Have a look at [NTwain](https://github.com/soukoku/ntwain) if you want something equivalent for Twain.
