### ISSUE TITLE
How to display progress bar using naps2-wia?

### ISSUE THREAD

**Issue by JohnDoe2193** [cyanfish/naps2-wia#10]
I use Xerox DocuMate 5445. This is a feeder-only document scanner, no flatbed component.

To scan I use the code that comes in naps2-wia Readme.MD pretty much as is. Everything works except I am not sure how to add a progress bar while pages are being scanned. I am using naps2-wia from Windows Forms application (.Net Framework)

Can you help? Thanks.

**Comment by cyanfish** [comment]
The WiaTransfer object has a [Progress event]( https://github.com/cyanfish/naps2-wia/blob/11126d5e07ac994a67bdcb9f52cafd34a7b278b2/NAPS2.Wia/WiaTransfer.cs#L20) you can listen to, and you can update a WinForms progress bar using that.
