### ISSUE TITLE
NAPS2.Wia.Native.dll Not found

### ISSUE THREAD

**Issue by martron1** [cyanfish/naps2-wia#5]
I tried running the example in my application and it threw "DllNotFoundException" with message: System.DllNotFoundException: 'Unable to load DLL 'NAPS2.Wia.Native.dll': The specified module could not be found. 

I am running Windows 11 and my project is using .Net framework 4.0.

**Comment by cyanfish** [comment]
NAPS2.Wia generates _win32 and _win64 folders in the output directories with that DLL. You'll need to make sure your project includes them. If you have a chain of project references you might need to reference it in the main project (e.g if you have `A > B > NAPS2.Wia` you might also need `A > NAPS2.Wia`).
