### ISSUE TITLE
More Examples / documentation request

### ISSUE THREAD

**Issue by Movian** [cyanfish/naps2-wia#7]
Hey,

I have been struggling for weeks to get a framework integrated with our application that supports Document Feeder scanning in a .net framework 4.8 app.

This is the first one I managed to get work (as there is no nuget package for NAPS2.SDK yet)

My one question is, is there any more documentation on naps2.WIA specifically?

It looks like there are events I can delegate for progress etc and just thought I would check if there are examples of that usage before I start diving into figuring everything out the slow way.

**Comment by Movian** [comment]
wrong location for this, my apologies.

**Comment by cyanfish** [comment]
You can perhaps look at the source for [WiaScanDriver](https://github.com/cyanfish/naps2/blob/master/NAPS2.Sdk/Scan/Internal/Wia/WiaScanDriver.cs) from NAPS2.Sdk, though keep in mind it's probably doing more than you need to (e.g. supporting both WIA 1.0 and 2.0).
