### ISSUE TITLE
How can one setup Bits/Pixel scanner property?

### ISSUE THREAD

**Issue by JohnDoe2193** [cyanfish/naps2-wia#8]
I use naps-wia with Xerox Documate 5445 scanner. It only has document feeder, no flatbed.

When using default settings it scans at 75 DPI in black-and-white (1 bit/pixel).

I was able to change resolution successfully using these calls:

            **item.SetProperty(WiaPropertyId.IPS_XRES, 300);
            item.SetProperty(WiaPropertyId.IPS_YRES, 300);**

However, I was not able to change Bit/Pixel to 24 in order to scan in color.

When I try the following:
      **item.SetProperty(4104, 24);**

I get this exception:

  **HResult=0x80070057
  Message=Could not set property 4104 (Bits Per Pixel) value to "24" (Parameter 'value')
  Source=NAPS2.Wia
  StackTrace:
   at NAPS2.Wia.WiaProperty.set_Value(Object value)
   at NAPS2.Wia.WiaExtensions.SetProperty(WiaItemBase item, Int32 propId, Int32 value)**

Can you help?

**Comment by cyanfish** [comment]
Try this:
`item.SetProperty(WiaPropertyId.IPA_DATATYPE, 3);`

**Comment by JohnDoe2193** [comment]
> Try this: `item.SetProperty(WiaPropertyId.IPA_DATATYPE, 3);`

Yes, this works. Thanks.

What are the other possible values other than **3**?

**Comment by cyanfish** [comment]
The doc is [here](https://learn.microsoft.com/en-us/windows-hardware/drivers/image/wia-ipa-datatype), but as far as the [actual values](https://github.com/cyanfish/naps2/blob/66c239b8298fc073872a747805f45f42645ba10f/NAPS2.Sdk/Scan/Internal/Wia/WiaScanDriver.cs#L306), 0 = black/white, 2 = grayscale, 3 = color.

**Comment by JohnDoe2193** [comment]
Thank you!
