### ISSUE TITLE
Is there a way to reset scanner to "default settings"?

### ISSUE THREAD

**Issue by JohnDoe2193** [cyanfish/naps2-wia#9]
Here is the code I use to scan (the scanner is Xerox Documate 5445 with a document feeder only):

`            using var deviceManager = new WiaDeviceManager();

            //var devices = deviceManager.GetDeviceInfos();

            var device = deviceManager.FindDevice("{6BDD1FC6-810F-11D0-BEC7-08002BE2092F}\\0000");

            // Prompt the user to select a scanner
            //using var device = deviceManager.PromptForDevice();

            // Select either "Flatbed" or "Feeder"
            using var item = device.FindSubItem("Feeder");

            // Scan all pages in the feeder at once
            item.SetProperty(WiaPropertyId.IPS_PAGES,
                             WiaPropertyValue.ALL_PAGES);
            int res = 75;
            item.SetProperty(WiaPropertyId.IPS_XRES, res);
            item.SetProperty(WiaPropertyId.IPS_YRES, res);

            //0 = black / white, 2 = grayscale, 3 = color.
            item.SetProperty(WiaPropertyId.IPA_DATATYPE, 3);

            // Enable duplex scanning
            item.SetProperty(WiaPropertyId.IPS_DOCUMENT_HANDLING_SELECT,
                             WiaPropertyValue.DUPLEX);

            int page = 1;
            // Set up the scan
            using var transfer = item.StartTransfer();
            transfer.PageScanned += (sender, args) =>
            {
                using (args.Stream)
                {
                    try
                    {
                        BitmapImage myBitmapImage = new BitmapImage();
                        myBitmapImage.BeginInit();
                        myBitmapImage.StreamSource = args.Stream;
                        myBitmapImage.CacheOption = BitmapCacheOption.OnLoad;
                        myBitmapImage.EndInit();
                        myBitmapImage.Freeze();
                        SavePage(myBitmapImage, "page" + page + ".jpg");
                        if(page ==1)
                        {
                            ScannedPage1.Source = myBitmapImage;
                            page++;
                        }
                        else
                            ScannedPage2.Source = myBitmapImage;

                    }
                    catch (Exception ex)
                    {
                        throw;
                    }
                }
            };

            // Do the actual scan
            transfer.Download();
`
Yesterday it worked just fine to scan both sides of the page. Today it only scanned one side of the page even though it is initialized as Duplex in the code above.

After a few attempts I powered off the scanner, powered it on and it started scanning both sides of the page again.

So my question is: is there some sort of API that resets the scanner the same way as if it was powered off and on?

Or do I possibly need to perform some additional initialization in my code?

**Comment by cyanfish** [comment]
I don't see anything obviously wrong with the code, though you can compare with the [naps2 code](https://github.com/cyanfish/naps2/blob/master/NAPS2.Sdk/Scan/Internal/Wia/WiaScanDriver.cs). Driver bugs are common with scanners.

You can maybe try running [naps2](https://www.naps2.com) and see if it has the same issue.
